small utility to convert matches from .bin to .txt or .txt to .bin
openMVG/openMVG pull request #1890
Opened 2021-04-30 12:42 UTC by yocabon

2021-05-06 20:47 UTC, pmoulon requested changes
Thank you for your contribution
I just advised some cleanup and directly using Load/Save function from the feature library files.
It will make the code even shorter and simpler.

2021-05-06 20:47 UTC, pmoulon commented on src/software/SfM/main_ConvertMatches.cpp
> +#include "openMVG/matching/svg_matches.hpp"
not needed

2021-05-06 20:47 UTC, pmoulon commented on src/software/SfM/main_ConvertMatches.cpp
> +#include "openMVG/image/image_io.hpp"
not needed

2021-05-07 09:33 UTC, yocabon reviewed
Done

2021-05-12 04:05 UTC, pmoulon commented
LGTM, thank you for your contribution

2021-05-12 04:06 UTC, merged